apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "acm-certificate-agent.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acm-certificate-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets/status"]
  verbs: ["get"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses/status"]
  verbs: ["get"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates/finalizers"]
  verbs: ["update"]