apiVersion: v1
kind: ServiceAccount
metadata:
  name: acm-certificate-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acm-certificate-agent.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{  required "IAM Role ARN must be supplied as value 'serviceAccount.iamRoleArn'." .Values.serviceAccount.iamRoleArn }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}